require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Naming/FileName:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Max: 6

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
