# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mpelos/ruby-node:2.4.1

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - apt-get update
          - apt-get install yarn
          - export PGHOST=localhost
          - bundle install
          - rails db:create db:migrate db:seed
          - RAILS_ENV=development rails webpacker:compile
          - rspec
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: investment-radar_development
        POSTGRES_USER: root
  caches:
    bundler: ./vendor