# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: starefossen/ruby-node

pipelines:
  custom: # Pipelines that are triggered manually
    everyday-build: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          caches:
            - bundler
            - node
          script:
            - ruby --version
            - export PGHOST=localhost
            - bundle install --jobs=2 --path vendor/bundle
            - yarn install
            - RAILS_ENV=test rails webpacker:compile
            - bundle exec rails db:setup
            - COV=YES bundle exec rspec
            - bundle exec rake quality:rubocop
            - bundle exec rake quality:reek
          services:
            - postgres
  branches:
    master:
      - step:
          caches:
            - bundler
            - node
          script:
            - ruby --version
            - export PGHOST=localhost
            - bundle install --jobs=2 --path vendor/bundle
            - yarn install
            - RAILS_ENV=test rails webpacker:compile
            - bundle exec rails db:setup
            - COV=YES bundle exec rspec
            - bundle exec rake quality:rubocop
            - bundle exec rake quality:reek
          services:
            - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: investment-radar_development
        POSTGRES_USER: root
  caches:
    bundler: vendor/bundle
